workflow dispatch

diff --git a/.github/workflows/03.Functions.yaml b/.github/workflows/03.Functions.yaml
--- a/.github/workflows/03.Functions.yaml
+++ b/.github/workflows/03.Functions.yaml
@@ -2,6 +2,7 @@ name: 09 - Using Functions
 
 on:
   push:
+  workflow_dispatch: 
 
 jobs:
   echo1:
@@ -19,6 +20,8 @@ jobs:
         run: echo "I am a bug fix"
       - name: Sleep for 20 seconds
         run: sleep 20
+    #   - name: Failing step
+    #     run: exit 1
       - name: I will be skipped
         if: ${{ success() }}
         run: echo "I will print if previous steps succeed."
@@ -31,3 +34,5 @@ jobs:
       - name: I will execute when cancelled
         if: ${{ cancelled() }}
         run: echo "I will print if the workflow has been cancelled."
+
+
